/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Cuenta;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;

/**
 *
 * @author SERVIDOR
 */
public class Principal5 extends javax.swing.JFrame {

    /**
     * Creates new form Principal5
     */
    Cuenta c;
    
   
    public Principal5() {
        initComponents();
        cmdActusald.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdGuardar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdIngresa.setEnabled(false);
        cmdRetirar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNidentf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNCuent = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdRetirar = new javax.swing.JButton();
        cmdIngresa = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdActusald = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSald = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtInteres = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("CUENTA BANCARIA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("No. de identificación:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtNidentf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNidentfActionPerformed(evt);
            }
        });
        txtNidentf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNidentfKeyTyped(evt);
            }
        });
        jPanel1.add(txtNidentf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 150, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("No. de la cuenta:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtNCuent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNCuentKeyTyped(evt);
            }
        });
        jPanel1.add(txtNCuent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setBackground(new java.awt.Color(255, 255, 102));
        cmdGuardar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdGuardar.setText("Crear cuenta");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, -1));

        cmdRetirar.setBackground(new java.awt.Color(255, 255, 102));
        cmdRetirar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 30));

        cmdIngresa.setBackground(new java.awt.Color(255, 255, 102));
        cmdIngresa.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdIngresa.setText("Ingresar");
        cmdIngresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresaActionPerformed(evt);
            }
        });
        jPanel2.add(cmdIngresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 30));

        cmdBorrar.setBackground(new java.awt.Color(255, 255, 102));
        cmdBorrar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 90, -1));

        cmdActusald.setBackground(new java.awt.Color(255, 255, 102));
        cmdActusald.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdActusald.setText("Actualizar saldo");
        cmdActusald.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActusaldActionPerformed(evt);
            }
        });
        jPanel2.add(cmdActusald, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        cmdMostrar.setBackground(new java.awt.Color(255, 255, 102));
        cmdMostrar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 180, 290));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Saldo inicial:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txtSald.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldKeyTyped(evt);
            }
        });
        jPanel1.add(txtSald, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 140, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 5));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRes.setEditable(false);
        txtRes.setColumns(20);
        txtRes.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtRes.setForeground(new java.awt.Color(153, 0, 153));
        txtRes.setRows(5);
        jScrollPane1.setViewportView(txtRes);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 310, 190));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Interes:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        txtInteres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInteresKeyTyped(evt);
            }
        });
        jPanel1.add(txtInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(589, 504));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
       String aux;
       long nidentf,ncuent;
       double sald,intr;
       
       if (txtNidentf.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"Digite su numero de identificacion","Error",JOptionPane.ERROR_MESSAGE);
           txtNidentf.requestFocusInWindow();
       }else if(txtNCuent.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Digite su numero de cuenta","Error",JOptionPane.ERROR_MESSAGE);
         txtNCuent.requestFocusInWindow();
       }else if (txtSald.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"Digite su saldo inicial","Error",JOptionPane.ERROR_MESSAGE);
           txtSald.requestFocusInWindow();
       }else if (txtInteres.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite el interes que aplicara","Error",JOptionPane.ERROR_MESSAGE);
         txtInteres.requestFocusInWindow();
       }else{
         nidentf=Long.parseLong(txtNidentf.getText());
         ncuent=Long.parseLong(txtNCuent.getText());
         sald=Double.parseDouble(txtSald.getText());
         intr=Double.parseDouble (txtInteres.getText());
         
         aux=c.mostrar();
         JOptionPane.showMessageDialog(this, aux);
         txtRes.setText(""+aux);
       }
       
        cmdActusald.setEnabled(true);
        cmdBorrar.setEnabled(true);
        cmdGuardar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdIngresa.setEnabled(true);
        cmdRetirar.setEnabled(true);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtInteres.setText("");
        txtNCuent.setText("");
        txtNidentf.setText("");
        txtRes.setText("");
        txtSald.setText("");
        
        txtNidentf.requestFocusInWindow();
        cmdActusald.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdGuardar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdIngresa.setEnabled(false);
        cmdRetirar.setEnabled(false);
        
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
       
       long nidentf,ncuent;
       double sald,intr;
       
       if (txtNidentf.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"Digite su numero de identificacion","Error",JOptionPane.ERROR_MESSAGE);
           txtNidentf.requestFocusInWindow();
       }else if(txtNCuent.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Digite su numero de cuenta","Error",JOptionPane.ERROR_MESSAGE);
         txtNCuent.requestFocusInWindow();
       }else if (txtSald.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"Digite su saldo inicial","Error",JOptionPane.ERROR_MESSAGE);
           txtSald.requestFocusInWindow();
       }else if (txtInteres.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite el interes que aplicara","Error",JOptionPane.ERROR_MESSAGE);
         txtInteres.requestFocusInWindow();
       }else{
         nidentf=Long.parseLong(txtNidentf.getText());
         ncuent=Long.parseLong(txtNCuent.getText());
         sald=Double.parseDouble(txtSald.getText());
         intr=Double.parseDouble (txtInteres.getText());
          
         c = new Cuenta (nidentf,sald,ncuent);
         JOptionPane.showMessageDialog(this, "Su informacion se ha guardado correctamente");
         
        cmdActusald.setEnabled(true);
        cmdBorrar.setEnabled(true);
        cmdGuardar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdIngresa.setEnabled(true);
        cmdRetirar.setEnabled(true);
       }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void txtNidentfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNidentfKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtNidentfKeyTyped

    private void txtNCuentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNCuentKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtNCuentKeyTyped

    private void txtSaldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtSaldKeyTyped

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
     double egreso,saldo;
       int rs;
       
       rs=JOptionPane.showConfirmDialog(this, "Seguro que desea retirar dinero?","Pregunta",JOptionPane.YES_NO_OPTION);
       if (rs==JOptionPane.YES_OPTION){
       saldo=Double.parseDouble(txtSald.getText());
       egreso=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite la cantidad de dinero que desea retirar"));
         if (egreso>saldo){
        JOptionPane.showMessageDialog(this, "No posee esta cantidad de dinero en su cuenta");
         }else{
         c.retirar(egreso);
       JOptionPane.showMessageDialog(this,"Retiro exitoso!");   
         } 
       txtSald.setText(""+c.getSaldact());
       }
       cmdActusald.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdGuardar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdIngresa.setEnabled(true);
        cmdRetirar.setEnabled(true); 
       
    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void txtInteresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInteresKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c) && c!=  '.') { 
              getToolkit().beep(); 
              evt.consume(); 
          }
          if (c ==  '.' && txtInteres.getText().contains(".")){
             evt.consume();  
          }
    }//GEN-LAST:event_txtInteresKeyTyped

    private void cmdActusaldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActusaldActionPerformed
        long nident,ncuent;
        double inter,saldf;
        int auxp;
         if (txtNidentf.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"Digite su numero de identificacion","Error",JOptionPane.ERROR_MESSAGE);
           txtNidentf.requestFocusInWindow();
       }else if(txtNCuent.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Digite su numero de cuenta","Error",JOptionPane.ERROR_MESSAGE);
         txtNCuent.requestFocusInWindow();
       }else if (txtSald.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"Digite su saldo inicial","Error",JOptionPane.ERROR_MESSAGE);
           txtSald.requestFocusInWindow();
       }else if (txtInteres.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite el interes que aplicara","Error",JOptionPane.ERROR_MESSAGE);
         txtInteres.requestFocusInWindow();
       }else{
         auxp= JOptionPane.showConfirmDialog(this, "Desea actualizar su saldo?","Pregunta",JOptionPane.YES_NO_OPTION);
         if (auxp == JOptionPane.YES_OPTION){
           nident=Long.parseLong(txtNidentf.getText());
           ncuent=Long.parseLong(txtNCuent.getText());
           saldf=Double.parseDouble(txtSald.getText());
           inter=Double.parseDouble(txtInteres.getText());
           c.retirar(inter);
           JOptionPane.showMessageDialog(this,"Saldo actualizado existosamente!");
           txtSald.setText(""+c.getSaldact());
         }else{
        cmdActusald.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdGuardar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdIngresa.setEnabled(true);
        cmdRetirar.setEnabled(true);  
         }
       }
    }//GEN-LAST:event_cmdActusaldActionPerformed

    private void txtNidentfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNidentfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNidentfActionPerformed

    private void cmdIngresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresaActionPerformed
        
       double ingreso;
       int rsp;
       
       rsp=JOptionPane.showConfirmDialog(this, "Seguro que desea ingresar dinero?","Pregunta",JOptionPane.YES_NO_OPTION);
       if (rsp==JOptionPane.YES_OPTION){
       ingreso=Double.parseDouble(JOptionPane.showInputDialog(this,"Digite la cantidad de dinero que va a ingresar"));
       c.ingresar(ingreso);
       JOptionPane.showMessageDialog(this,"Ingreso exitoso!");
       
       txtSald.setText(""+c.getSaldact());
       }else{
        cmdActusald.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdGuardar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdIngresa.setEnabled(true);
        cmdRetirar.setEnabled(true);  
       }
    }//GEN-LAST:event_cmdIngresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActusald;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdIngresa;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtNCuent;
    private javax.swing.JTextField txtNidentf;
    private javax.swing.JTextArea txtRes;
    private javax.swing.JTextField txtSald;
    // End of variables declaration//GEN-END:variables
}
