/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.Cuenta;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JOptionPane;

/**
 *
 * @author SERVIDOR
 */
public class Principal5 extends javax.swing.JFrame {

    /**
     * Creates new form Principal5
     */
    
   
    public Principal5() {
        initComponents();
        cmdActusald.setEnabled(true);
        cmdBorrar.setEnabled(true);
        cmdGuardar.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdIngresa.setEnabled(true);
        cmdRetirar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNidentf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNCuent = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdRetirar = new javax.swing.JButton();
        cmdIngresa = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdActusald = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSald = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtInteres = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("CUENTA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel2.setText("No. de Indentificación:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtNidentf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNidentfKeyTyped(evt);
            }
        });
        jPanel1.add(txtNidentf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 150, 30));

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel3.setText("No. de la Cuenta:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        txtNCuent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNCuentKeyTyped(evt);
            }
        });
        jPanel1.add(txtNCuent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 150, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setBackground(new java.awt.Color(255, 255, 153));
        cmdGuardar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, -1));

        cmdRetirar.setBackground(new java.awt.Color(255, 255, 153));
        cmdRetirar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdRetirar.setText("Retirar");
        cmdRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetirarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 90, 30));

        cmdIngresa.setBackground(new java.awt.Color(255, 255, 153));
        cmdIngresa.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdIngresa.setText("Ingresar");
        jPanel2.add(cmdIngresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 90, 30));

        cmdBorrar.setBackground(new java.awt.Color(255, 255, 153));
        cmdBorrar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 90, -1));

        cmdMostrar.setBackground(new java.awt.Color(255, 255, 153));
        cmdMostrar.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        cmdActusald.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        cmdActusald.setText("Actualizar saldo");
        cmdActusald.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdActusaldActionPerformed(evt);
            }
        });
        jPanel2.add(cmdActusald, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 180, 280));

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel6.setText("Saldo inicial:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtSald.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldKeyTyped(evt);
            }
        });
        jPanel1.add(txtSald, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRes.setColumns(20);
        txtRes.setRows(5);
        jScrollPane1.setViewportView(txtRes);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, 150));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 310, 190));

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel4.setText("Interes:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        txtInteres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInteresKeyTyped(evt);
            }
        });
        jPanel1.add(txtInteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(589, 482));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
       Cuenta ct,ms;
       String mt;
       int nidentf,ncuent;
       double sald,intr;
       
       if (txtNidentf.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"Digite su numero de identificacion","Error",JOptionPane.ERROR_MESSAGE);
           txtNidentf.requestFocusInWindow();
       }else if(txtNCuent.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Digite su numero de cuenta","Error",JOptionPane.ERROR_MESSAGE);
         txtNCuent.requestFocusInWindow();
       }else if (txtSald.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"Digite su saldo inicial","Error",JOptionPane.ERROR_MESSAGE);
           txtSald.requestFocusInWindow();
       }else if (txtInteres.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite el interes que aplicara","Error",JOptionPane.ERROR_MESSAGE);
         txtInteres.requestFocusInWindow();
       }else{
         nidentf=Integer.parseInt(txtNidentf.getText());
         ncuent=Integer.parseInt(txtNCuent.getText());
         sald=Double.parseDouble(txtSald.getText());
         intr=Double.parseDouble (txtInteres.getText());
         
         ct=new Cuenta (nidentf,sald,intr,ncuent);
          ms=ct.mostrar();
          mt="No. Identificacion: "+ct.getNidentf()+ "\n" +"No. de la cuenta: "+ct.getNcuenta()+"\n"
             + "Saldo actual: "+ct.getSaldact()+ "Interes: " +ct.getIntanual();
          txtRes.setText(mt);
                  
         
       }
       
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtInteres.setText("");
        txtNCuent.setText("");
        txtNidentf.setText("");
        txtRes.setText("");
        txtSald.setText("");
        
        txtNidentf.requestFocusInWindow();
        
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
         Cuenta ct;
       int nidentf,ncuent;
       double sald,intr;
       
       if (txtNidentf.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"Digite su numero de identificacion","Error",JOptionPane.ERROR_MESSAGE);
           txtNidentf.requestFocusInWindow();
       }else if(txtNCuent.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this, "Digite su numero de cuenta","Error",JOptionPane.ERROR_MESSAGE);
         txtNCuent.requestFocusInWindow();
       }else if (txtSald.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this,"Digite su saldo inicial","Error",JOptionPane.ERROR_MESSAGE);
           txtSald.requestFocusInWindow();
       }else if (txtInteres.getText().trim().isEmpty()){
         JOptionPane.showMessageDialog(this,"Digite el interes que aplicara","Error",JOptionPane.ERROR_MESSAGE);
         txtInteres.requestFocusInWindow();
       }else{
         nidentf=Integer.parseInt(txtNidentf.getText());
         ncuent=Integer.parseInt(txtNCuent.getText());
         sald=Double.parseDouble(txtSald.getText());
         intr=Double.parseDouble (txtInteres.getText());
          
         ct = new Cuenta (nidentf,sald,intr,ncuent);
         JOptionPane.showMessageDialog(this, "Su informacion se ha guardado correctamente");
         
       }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void txtNidentfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNidentfKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtNidentfKeyTyped

    private void txtNCuentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNCuentKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtNCuentKeyTyped

    private void txtSaldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
              evt.consume(); 
          }
    }//GEN-LAST:event_txtSaldKeyTyped

    private void cmdRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetirarActionPerformed
       Cuenta r,sald;
       int nident,ncuent;
       double saldo, intr,ns;
       
    
       
       
    }//GEN-LAST:event_cmdRetirarActionPerformed

    private void txtInteresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInteresKeyTyped
        char c=evt.getKeyChar(); 
          if(!Character.isDigit(c) && c!=  '.') { 
              getToolkit().beep(); 
              evt.consume(); 
          }
          if (c ==  '.' && txtInteres.getText().contains(".")){
             evt.consume();  
          }
    }//GEN-LAST:event_txtInteresKeyTyped

    private void cmdActusaldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdActusaldActionPerformed
        Cuenta sald,rs;
        int nident,ncuent,res;
        double inter,aux,saldf,ns;
        
        res = JOptionPane.showConfirmDialog(this, "Desea actualizar su saldo?","Pregunta",JOptionPane.YES_NO_OPTION);
         if (res==JOptionPane.YES_OPTION){
       nident=Integer.parseInt(txtNidentf.getText());
       ncuent=Integer.parseInt(txtNCuent.getText());
       saldf=Double.parseDouble(txtSald.getText());
       inter=Double.parseDouble(txtInteres.getText());
      
       rs=new Cuenta (nident,saldf,inter,nident);
       ns=rs.actsaldo();
       rs.setSaldact(ns);
       JOptionPane.showMessageDialog(this, "Se ha guardado nuevo saldo");
       txtSald.setText("" +ns);
       txtRes.setText("");

         }
    }//GEN-LAST:event_cmdActusaldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdActusald;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdIngresa;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtInteres;
    private javax.swing.JTextField txtNCuent;
    private javax.swing.JTextField txtNidentf;
    private javax.swing.JTextArea txtRes;
    private javax.swing.JTextField txtSald;
    // End of variables declaration//GEN-END:variables
}
